name: Shoobox
favicon: null
layout_spectrum: 0.9359
typography_spectrum: 0.5464143480639905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#ffffff'
    - '#b0a087'
    - '#6283b8'
    - '#e3213c'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
