name: Shoobox
favicon: null
layout_spectrum: 0.889448209432885
typography_spectrum: 0.5464143480639905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8723572958260775
  lightness: 0.5301478567998856
  saturation: 0.5940320920199156
  rhythmicContrast: 0.4104322586208582
purpose: []
